FROM python:3.13-bookworm

WORKDIR /app
COPY . /app

RUN pip install snmpsim

RUN groupadd --gid 1001 nonroot && useradd --uid 1001 --gid 1001 --no-create-home nonroot

USER nonroot

EXPOSE 161/udp

ENTRYPOINT [ "snmpsim-command-responder", "--data-dir=./data", "--agent-udpv4-endpoint=0.0.0.0:161" ]
