services:
  et-envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: et-envoy # envoy hostname
    ports:
      - "9901:9901/tcp" # admin interface
      - "10161:10161/udp" # udp listener
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - et-network
  et-udp:
    image: huangsam/et-udp:dev
    container_name: et-udp # go hostname
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - et-network

networks:
  et-network: # shared network
    driver: bridge
