name: envoy-trial
services:
  udp-gateway: # envoy service name
    image: envoyproxy/envoy:v1.33-latest
    ports:
      - "9901:9901/tcp" # admin interface port
      - "10161:10161/udp" # udp listener port
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - udp-delegate
    networks:
      - shared
  udp-delegate: # service name
    image: trial-udp-delegate:latest
    build:
      context: .
      dockerfile: Dockerfile.delegate # golang
    depends_on:
      - snmp-simulator
    networks:
      - shared
  snmp-simulator: # service name
    image: trial-snmp-simulator:latest
    build:
      context: .
      dockerfile: Dockerfile.simulator # python
    networks:
      - shared

networks:
  shared: # shared network
    driver: bridge
