services:
  et-envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: et-envoy # envoy proxy hostname
    ports:
      - "9901:9901/tcp" # admin interface port
      - "10161:10161/udp" # udp listener port
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - et-udp
    networks:
      - et-network
  et-udp:
    image: huangsam/et-udp:dev
    container_name: et-udp # udp proxy hostname
    build:
      context: .
      dockerfile: Dockerfile.proxy # golang
    depends_on:
      - et-sim
    networks:
      - et-network
  et-sim:
    image: huangsam/et-sim:dev
    container_name: et-sim # snmp simulator hostname
    build:
      context: .
      dockerfile: Dockerfile.simulator # python
    networks:
      - et-network

networks:
  et-network: # shared network
    driver: bridge
